### ISSUE TITLE
Appendix C Usefulness

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#14]
> The sample messages in C do not seem useful, as they seem to be repeating
just the packet layouts.  I do not understand what the "Hex" values in
C.3 mean and there seems to be no way to re-compute/verify them.

**Comment by kc2rxo** [comment]
Initial response:

> They were added to give context for someone who may have a hard time grokking the packet layouts and the various nesting. The hex values were taken from a running implementation log of such messages to give an example of what would be seen over the air.

**Comment by kc2rxo** [comment]
Does anyone have a strong urge to keep or remove Appendix C?

**Comment by boucadair** [comment]
I tend to agree with Rich on this one C1/C2. 

One of the "hex" examples in C3 can be called directly in the core text when link message is discussed (assuming some narrative text is added to explain what that hex is about)

**Comment by kc2rxo** [comment]
This has been addressed in -07 just posted.
