### ISSUE TITLE
Unix Timestamp

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#16]
> Sec 5, "UNIX timestamp offset by ..." you mean Unix-style timestamp
but with an epoch of ... right?  Is the "UA signature" defined
somewhere?  Same question about the signatures in Sec 6, etc.

**Comment by kc2rxo** [comment]
Initial response:

> Yes a Unix-style timestamp. I will adjust the wording.
>
> The structure in Section 5 is more formally defined in draft-ietf-drip-registries. This section is more of an abbreviated "copy-paste" of it so its inline in this document. It's just in this document I explicitly set certain field values that are different from the other document.

**Comment by rgmhtt** [comment]
fixed
