### ISSUE TITLE
Explain why it makes sense to define an IETF extension to a scheme that is defined in an external body (ASTM). 

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#2]
From Med

**Comment by kc2rxo** [comment]
First pass at addressing in 0f4a464f697538ad22c22ecd496207ba1bc980ba

**Comment by boucadair** [comment]
https://github.com/ietf-wg-drip/draft-ietf-drip-auth/commit/0f4a464f697538ad22c22ecd496207ba1bc980ba is great. However, we don't include enough arguments why this couldn't be done directly in the ASTM.

**Comment by kc2rxo** [comment]
This has been updated again - with a little more context in https://github.com/ietf-wg-drip/draft-ietf-drip-auth/commit/1496431f936eb498a703b6000d3c289e5e971038

**Comment by rgmhtt** [comment]
ASTM has defined Authentication schemes open to other SDOs.  We now have text covering this and why we are doing it here.

**Comment by boucadair** [comment]
Thanks @kc2rxo and @rgmhtt. This is better.
