### ISSUE TITLE
RID is normative

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-auth#24]
Consider adding a pointer for DET + list it as normative

```
   UA DRIP Entity Tag (16-bytes):  The UA DET in byte form (network byte
      order) and is part of Figure 4.
```

**Comment by kc2rxo** [comment]
Would -arch and -reqs also be considered normative? I plan to keep -registries informative.

**Comment by boucadair** [comment]
We can keep arch and req as informative for now. 

OK with your plans for -registries.

**Comment by kc2rxo** [comment]
I just noticed after pushing that RFC9153 and -arch are both actually normative; should or switch or make an action item for the interim?
