### ISSUE TITLE
notations not defined in the Reg I-D

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-auth#27]
The draft uses notations such as DIME:Apex but this is not defined (currently) in the reg I-D

**Comment by kc2rxo** [comment]
I believe this is sorted in the most recent -registries (-07)? Maybe I am wrong.

If not would adding a section to -registries to describe the text format of "DIME:<Role>" be appropriate?

**Comment by boucadair** [comment]
> If not would adding a section to -registries to describe the text format of "DIME:" be appropriate?

I like this. Thanks.

**Comment by kc2rxo** [comment]
I will close this issue here - as this is now a -reg only issue.
