### ISSUE TITLE
DIME, DET, HHIT, HI

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-auth#30]
* May include some informative text to articulate these various concept with pointer to RID/ARCH specs. This does not need to be long. 
* Suggest using DET and remove any hhit mention 
* What is a "DIME's DET", "DIME's HI"?

**Comment by kc2rxo** [comment]
I can find somewhere to add these concepts.

I also agree with DET replacing HHIT anywhere in the text as appropriate. DET for when discussing the use case and HHIT when specifically discussing the technology.

Its the DET or HI being used by a DRIP Identity Management Entity (DIME).

**Comment by kc2rxo** [comment]
@boucadair can you review -29 and confirm this has been dealt with enough for you?

From a quick search "HHIT" has been changed to "DET" everywhere except in one place where it makes sense.

**Comment by boucadair** [comment]
Thanks. 

> What is a "DIME's DET", "DIME's HI"?

You may link these, e.g., to ths

>      DRIP Entity Tag of DIME: (16-bytes)
>          DET of DIME.
> 
>      DRIP Entity Tag of UA: (16-bytes)
>          DET of UA.
> 
>      Host Identity of UA: (32-bytes)
>          HI of UA.

I still think that some of these can be introduced earlier in the document with appropriate refs to -RID. 

BTW, please move rid to be listed as normative.

**Comment by kc2rxo** [comment]
I have added the definitions into the Definitions section of -auth.

-rid is already marked as normative.
