### ISSUE TITLE
category: info

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#34]
I have noticed at some point the category of this document has changed from "std" to "info".

I must of done it, but was it an accidental thing or intentional?

I presume we want this document to be "std".

**Comment by boucadair** [comment]
Yes, please fix that. Thanks. 

This would be aligned with the metadata we entered for this draft at: https://datatracker.ietf.org/doc/draft-ietf-drip-auth/ (see Intended RFC status)

**Comment by kc2rxo** [comment]
This is fixed in -30.
