### ISSUE TITLE
Previous Hash Value

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#36]
For the first Manifest there is no previous hash value to use.

Should it be:

1. Null - current selection in text
2. Broadcast Endorsement: HDA on UA
3. Self-Endorsement: UA
4. Lower 64-bits of DET
5. Random nonce
6. Other?

**Comment by kc2rxo** [comment]
Another hanging item from -30. Do we have any preference?

**Comment by kc2rxo** [comment]
It seems after some discussion with authors that option 5 may be the best. Bob's mailing list response is quoted below.

> Now as to what should be the value of the first Previous hash value.  Should it be NULL as currently specified?
> 
> We comment that these lists of signed hashes, including the hash of the prior list, is similar to a blockchain.  What is the practice in blockchains?  How do the chains start?  I have no experience and have no documents to research this.  Do others know?
> 
> Cryptographically, we avoid having a set of hashes all start out with the same value, particularly a string of zeros.  This is closely related to the attacks on MD5, but I would have to spend cycles to determine how close.  And hashing often starts with some non-repeating IV (what does the I stand for?).  That said, sponges are really good at defeating attacks of this nature.  The SHA2 construct is as well.  It is not considered cryptographically necessary to NOT use a string of zeros to start out a string to hash.
> 
> But what does it cost to avoid a possible future attack against the hash.  What does it take to use a random initial value?  Nothing?
> 
> But then you don't "know" this is the first block in the chain.  But does that really matter?  I think not.  Where would such a ledger even be kept that started with the first manifest which probably occurred before takeoff.
> 
> Thus after all this rambling, explaining my thoughts,,,   I say use a random value for the first Previous hash value.
> 
> Bob

**Comment by boucadair** [comment]
@kc2rxo, any action is needed here or should the issue be closed?

**Comment by kc2rxo** [comment]
A random nonce has been selected and was added in -32
