### ISSUE TITLE
Appendix E.1: Methodology

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#38]
There was the following comment in the draft:

> do we regard the the set when sent twice a second as a retransmission or as an update?

I believe this was in reference to discussions with @cardsw personally during the writing process of this section. 

Basically the basic set of messages (Basic ID, Location and System) are mandated for at least 1Hz. Would just "duplicating" said set in the same second count or would they need to be different messages and count as a new set?

**Comment by kc2rxo** [comment]
I believe this is still an open question.

**Comment by kc2rxo** [comment]
Asked over at the ODID GitHub to see what people think. [1]

[1] https://github.com/opendroneid/opendroneid-core-c/issues/71

**Comment by kc2rxo** [comment]
I think after some discussion with the authors that an informational note needs to be added to D.1 that states the problems with increasing the transmit rate and basically be a word of warning that increasing it too far would be discouraged.

**Comment by boucadair** [comment]
@kc2rxo, any action is needed here?

**Comment by kc2rxo** [comment]
Was missed. I added text in -34 which was just posted.
