### ISSUE TITLE
SAM Type Allocations

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#39]
SAM Type needs allocations from the designated ASTM registrar.

**Comment by kc2rxo** [comment]
F3411-22a SAM Type is a byte field defined as follows:

0: Reserved
1 - 224: Allocated by Registrar
225 - 255: Experimental/Private Use

To remove the hold on -auth due to no registrar to get the allocations from we can use the "Experimental/Private Use" range to get our standard through then go back and update the document when we can get proper allocations.

**Comment by kc2rxo** [comment]
A more abstract view of this from @cardsw:

DRIP Authentication is proposed as an IETF standard, _not_ experimental.

It can and typically will be used together with an external SDO's standard (ASTM F3411), also _not_ experimental.

Initially, this joint use (only) of these standards _is_ experimental, but only in the sense that it uses experimental/private use codepoints of the external (framing) standard to identify DRIP as the encapsulated authentication method.

This is comparable to IPv4 being a standard & Ethernet / IEEE 802.3 (yes I know they are not exactly the same thing) being a standard but the Ethertype value of 0x0800 for IPv4 is not in the official IEEE list of Ethertypes.

We propose to be better behaved than that, by using values from the external standard's experimental/private allocation until such time as the external SDO stands up its registrar, at which time we will obtain (i.e., we will request, and have already been assured we will be granted) non-experimental assignments.

**Comment by kc2rxo** [comment]
Some clarifications from Eric via email.

If we do this path. We will need to mark the document as "experimental". Then perform what is needed.

We shall wait till IETF116 to decide the documents fate with the hope progress is made to avoid this situation entirely.

**Comment by cardsw** [comment]
I would hate for -auth to be experimental:
it presumably can't be cited in a regulatory MOC if it is.

My argument is that neither F3411 nor -auth is experimental:
only the combination of the two is, and that only temporarily;
but if Eric says that won't fly, let's hold until IETF 116,
with both proposed standard and experimental versions ready.

> Some clarifications from Eric via email.
>
> If we do this path. We will need to mark the document as "experimental".
> Then perform what is needed.
>
> We shall wait till IETF116 to decide the documents fate with the hope
> progress is made to avoid this situation entirely.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/ietf-wg-drip/draft-ietf-drip-auth/issues/39#issuecomment-1457003095
> You are receiving this because you were mentioned.
>
> Message ID:
> ***@***.***>


-- 
Stuart W. Card, VP & Chief Scientist
Critical Technologies Inc. (CTI)
***@***.***>

**Comment by kc2rxo** [comment]
Code points are being assigned. This issue will be closed once official word comes back from ICAO and the document updates in -31 to add the values.

**Comment by boucadair** [comment]
I remember that we discussed having an IANA registry that mirror what is assigned by ASTM. Did we reach a conclusion on that one?

**Comment by kc2rxo** [comment]
So just to be clear on the ICAO website [1] we have been granted SAM Types 1-4. Looks like they did not specify which format from DRIP Auth is which so I guess we get to choose (yay?).

So to me it seems like we need to mirror the registry to give the code points actual meaning that is directly in the draft. The registry (and draft) would point directly to ICAO to ensure the allocation path can be followed from least specific (ICAO) to most specific (the draft/IANA).

[1] https://www.icao.int/airnavigation/IATF/Pages/ASTM-Remote-ID.aspx

**Comment by boucadair** [comment]
> So to me it seems like we need to mirror the registry to give the code points actual meaning that is directly in the draft. The registry (and draft) would point directly to ICAO to ensure the allocation path can be followed from least specific (ICAO) to most specific (the draft/IANA).

Looks good to me.
