### ISSUE TITLE
Early IANA review/IETF#116

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-auth#41]
From IANA

> Dear Authors,
> 
> Before the IETF meeting, we check working group agendas for documents with IANA-related issues. We have a note about the current version of this document:
> 
> https://datatracker.ietf.org/doc/html/draft-ietf-drip-auth
> 
> It appears that in the IANA Considerations section, “registry” should be changed to “registry group,” and “subregistry” to “registry.” See the “Terminology” section at 
> 
> https://www.iana.org/help/protocol-registration
> 
> If you have any questions, just let us know. If you'd like to talk in person, you can find us next to the RFC Editor's table from Monday through Thursday. You can also request another review at any time by contacting us at [iana@iana.org](mailto:iana@iana.org).
> 
> Best regards,
> 
> Amanda Baber
> IANA Operations Manager

**Comment by kc2rxo** [comment]
This is now fixed in -31 commit: c46ebcf
