### ISSUE TITLE
Rapidly Changing Wording

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#44]
From MCR on list:

> } A message containing rapidly changing, unpredictable but sanity-checkable
> } data, signed by that key, provides trust that some agent with
> } access to
> } that data also possesses that key.
> 
> I don't know if the word "rapidly changing" is relevant.
> I think you are trying to say that the data changes, and at a rate that is
> frequent enough that there isn't some kind of sneaker net or crypto-attack
> going on, is your point.   I don't know if it matters that it is unpredictable.
> If a UAV is moving North, one might predict that the lattitude might be
> predictably going up, but also changing at a "sanity checkable" amount.
> (so, probably not above Mach 2)
> 
> Maybe just say:
> 
> > A sequence of messages containing changing, but sanity-checkable
> } data, signed by the same key, provides trust that some agent with access to
> } that data also possesses that key.
> 
> Maybe:
> } (or is collaborating with or observed in real time by)
> 
> this could be a separate sentence, or maybe it just goes into the Security
> Considerations.

**Comment by boucadair** [comment]
I lost the context if this one was covered in the latest version? If so, please link to the commit that fixed and then close. Thanks

**Comment by kc2rxo** [comment]
Again, lost in ML between Stu and MCR. Not really sure they even got to it.

**Comment by cardsw** [comment]
Yes, I have defended my position on the list, in the past week. That's all I can do.

**Comment by kc2rxo** [comment]
I want to get this issue closed in v41 as it was missed in v40.

This is the original offending text:
```
A message containing rapidly changing, unpredictable but sanity-checkable data, signed by that key, provides trust that some agent with access to that data also possesses that key.
```
Stu, from the list and his defense wishes to keep the text as is.
MCR, from the list wishes the following change:

```suggestion
A sequence of messages containing changing, but sanity-checkable data, signed by the same key, provides trust that some agent with access to that data also possesses that key.
```

**Comment by mcr** [comment]
I didn't like the word unpredictable.  I think the data, for it to be sanity checkable, has to be predictable.
I re-read: https://www.ietf.org/archive/id/draft-ietf-drip-auth-40.html#section-6.4.2
I can live with that word there, if I'm in the rough here.
#57 seems to contain text that I like.

**Comment by cardsw** [comment]
Perhaps our different perspectives are a matter of time scale?

If the data is predictable so far in advance that it enables brute force
attacks (which won't be geologic time once quantum attacks are practical),
that's bad.

If the data is not "predictable" on a very short time scale, such as the
UA still being, at the time an Observer sanity checks a reported position,
within a few meters of where it was when the UA determined its position to
sign & send a report, that is also bad.

Would "not predictable far in advance (relative to typical operational
flight times)" be acceptable to all?



> I didn't like the word unpredictable.  I think the data, for it to be
> sanity checkable, has to be predictable.
> I re-read:
> https://www.ietf.org/archive/id/draft-ietf-drip-auth-40.html#section-6.4.2
> I can live with that word there, if I'm in the rough here.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/ietf-wg-drip/draft-ietf-drip-auth/issues/44#issuecomment-1831940772
> You are receiving this because you commented.
>
> Message ID:
> ***@***.***>


-- 
Stuart W. Card, VP & Chief Scientist
Critical Technologies Inc. (CTI)
***@***.***>

**Comment by cardsw** [comment]
We are trying to avoid 2 attacks on the process of using out-of-band 
information to validate that the observed UA actually holds the private 
key associated with its claimed ID:

(1) replay attacks, which are possible if the nonce-like signed data is 
not guaranteed (at least with very high probability) to be _novel_; and

(2) brute force attacks, which are likely to become possible with 
quantum computing if the signed data is predictable _far in advance_.


On 11/29/2023 9:52 AM, Stuart William Card wrote:
> Perhaps our different perspectives are a matter of time scale?
> 
> If the data is predictable so far in advance that it enables brute force
> attacks (which won't be geologic time once quantum attacks are practical),
> that's bad.
> 
> If the data is not "predictable" on a very short time scale, such as the
> UA still being, at the time an Observer sanity checks a reported position,
> within a few meters of where it was when the UA determined its position to
> sign & send a report, that is also bad.
> 
> Would "not predictable far in advance (relative to typical operational
> flight times)" be acceptable to all?
> 
> 
> 
>> I didn't like the word unpredictable.  I think the data, for it to be
>> sanity checkable, has to be predictable.
>> I re-read:
>> https://www.ietf.org/archive/id/draft-ietf-drip-auth-40.html#section-6.4.2
>> I can live with that word there, if I'm in the rough here.
>>
>> --
>> Reply to this email directly or view it on GitHub:
>> https://github.com/ietf-wg-drip/draft-ietf-drip-auth/issues/44#issuecomment-1831940772
>> You are receiving this because you commented.
>>
>> Message ID:
>> ***@***.***>
> 
> 

-- 
Stuart W. Card, PhD: VP & Chief Scientist, Critical Technologies Inc.
Superior Engineering Solutions for Trustworthy Networked Autonomy
* Creativity * Diversity * Expertise * Flexibility * Integrity *
Suite 400 Technology Center, 4th Floor 1001 Broad St, Utica NY 13501
315-793-0248 x141 FAX -9710 ***@***.***> www.critical.com
