### ISSUE TITLE
Introduction Missing Authentication

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#45]
From MCR on list: 

> A diff from the previous version is available at:
> https://author-tools.ietf.org/iddiff?url2=draft-ietf-drip-auth-31
> The first diff block contains text about claims.
> It seems that it has lost the words: "Without authentication"
> which I think was an important thing to say.

**Comment by boucadair** [comment]
What is the status of this item?

**Comment by kc2rxo** [comment]
It was in limbo in the mailing list between MCR and Stu.

I will re-ping that email chain to see what everyone thinks.

**Comment by cardsw** [comment]
I re-wrote that paragraph to clear up a misunderstanding. My rewrite put things in what is, to me, a logical sequence. To bring authentication back into the discussion, we could add it at the end of the paragraph, e.g., "Authentication is intended to address this issue." or perhaps "Authentication is the primary strategy for mitigating this issue."

**Comment by kc2rxo** [comment]
Fixed in 3a5614c1cdff4cd898f8473c76dec19c9161a6d9 as was missing in v40
