### ISSUE TITLE
idnits

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-auth#47]
Please check these and fix as appropriate: 
 
 Checking nits according to https://www.ietf.org/id-info/checklist :
  ----------------------------------------------------------------------------

  ** There are 5 instances of too long lines in the document, the longest one
     being 76 characters in excess of 72.

  Miscellaneous warnings:
  ----------------------------------------------------------------------------

  -- Found something which looks like a code comment -- if you have code
     sections in the document, please surround them with '<CODE BEGINS>' and
     '<CODE ENDS>' lines.

  Checking references for intended status: Proposed Standard
  ----------------------------------------------------------------------------
  ** Downref: Normative reference to an Informational RFC: RFC 9153

  ** Downref: Normative reference to an Informational RFC: RFC 9434

**Comment by kc2rxo** [comment]
I feel like RFC9153 (requirements) and RFC9434 (architecture) are very much normative just by their very nature. Why are they being marked to downref?

**Comment by kc2rxo** [comment]
Fixed the long lines: 1ac73a0ce6d9135c6c363813614adae2078a91da

**Comment by kc2rxo** [comment]
I can not seem to find the issue with the code fences?

**Comment by boucadair** [comment]
> I feel like RFC9153 (requirements) and RFC9434 (architecture) are very much normative just by their very nature. Why are they being marked to downref?

Because those are published as Informational RFCs. As per https://www.ietf.org/about/groups/iesg/statements/normative-informative-references/, the criteria are: "Normative references specify documents that must be read to understand or implement the technology in the new RFC, or whose technology must be present for the technology in the new RFC to work. An informative reference is not normative; rather, it only provides additional information. For example, an informative reference might provide background or historical information. Informative references are not required to implement the technology in the RFC."

Looking into the text, I don't think there are solid arguments to list RFC9434 as normative. 

Please note that rfc9374 cites these two as informative.

**Comment by kc2rxo** [comment]
Down referenced both RFCs as recommended: b8c484ef84ae58c1fe656c5273fae8ea34285e7c

**Comment by boucadair** [comment]
> ** There are 5 instances of too long lines in the document, the longest one
> being 76 characters in excess of 72.

Please fix this part as well.

**Comment by kc2rxo** [comment]
Line lengths are now fixed: bc2d80a57504715e92112101fac3488d9ad1afd7
