### ISSUE TITLE
When it is safe to ignore SHOULD validate here

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-auth#53]
https://github.com/ietf-wg-drip/draft-ietf-drip-auth/blob/a15a80d0a62ba0118a40b81e44f61b302566fde2/auth.mkd?plain=1#L181

Why this not a MUST?

**Comment by kc2rxo** [comment]
Resolved in 4d54102d39ddcb8d3e84109f1de1d65432d3d55a
