### ISSUE TITLE
Why validation is not MUST here?

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-auth#54]
https://github.com/ietf-wg-drip/draft-ietf-drip-auth/blob/a15a80d0a62ba0118a40b81e44f61b302566fde2/auth.mkd?plain=1#L191

**Comment by boucadair** [comment]
Please check other uses of SHOULD in the document and consider turning those to MUST or add an explanation about conditions under which it is safe to ignore the SHOULD. Fixing those now will save us some cylces in the IESG review. Thanks.

**Comment by kc2rxo** [comment]
Fixed the highlighted SHOULD in 96822d88967f6f30f168d3cd3b07dbd9c99141e9.
