### ISSUE TITLE
Define Manifest

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#64]

**Comment by evyncke** [comment]
the current PR does not include manifest, nothing dramatic / blocking but would be useful for the reader

**Comment by kc2rxo** [comment]
I shall have a definition later today then as I am meeting with Stu.

I suspected that the use of manifest in Section 4.4 would be enough but we can add something.

**Comment by kc2rxo** [comment]
Added in 4194b50b0f8a2259539406d34424013b7075a298

**Comment by kc2rxo** [comment]
With a definition added I am closing this issue. If there are issues with said definition a new issue can be opened.
