### ISSUE TITLE
Broader Section Titles

### ISSUE THREAD

**Issue by kc2rxo** [ietf-wg-drip/draft-ietf-drip-auth#9]
Rich Salz:

> There are far too many one-paragraph sections.  Come up with broader titles
and merge things a bit; I think it will read better. I know kthis is not a
trivial amount of work.

**Comment by kc2rxo** [comment]
Initial response:

> This was a stylistic choice on my part so good to hear some feedback on it.
>
> My intention was that specific fields that are later referenced in the document to explicitly state what nests into what would be easier with section headers for them rather than pointing to a general section and have to dig through some text in section to figure things out.

**Comment by kc2rxo** [comment]
After re-reading the document with fresh eyes personally I feel it flows fine as it is.

Does anyone have any other strong opinions on this?

**Comment by rgmhtt** [comment]
I think we have largely addressed this item.  Still some short sections, but actually text added to some for clarity.
